### ISSUE TITLE
java.lang.NoClassDefFoundError: java/util/Base64

### ISSUE THREAD

**Issue by SSSang2** [SSSang2/Thumbnail#9]
Base64를 지원하는java/util/Base64 클래스가 CentOs에 없는듯..

**Comment by SSSang2** [comment]
import org.apache.tomcat.util.codec.binary.Base64;
Base64.encodeBase64String(b);
사용.

**Comment by linkstack** [comment]
An advice: We can update to Java 8 or use Base64 from Apache Commons Codec, like this post [java.lang.NoClassDefFoundError: java/util/Base64](http://redino.net/blog/2018/08/java-lang-noclassdeffounderror-java-util-base64/)
